branch-defaults:
  default:
    environment: namabayiApp3Env
    group_suffix: null
global:
  application_name: namabayiApp3
  default_ec2_keyname: null
  default_platform: python2.7
  default_region: eu-west-1
  profile: null
  sc: null
